---
apiVersion: v1
kind: Service
metadata:
  name: post
spec:
  type: LoadBalancer
  selector:
    app: post
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/my-repository/post:latest
          ports:
            - containerPort: 8080